/**
 * Generates backend/schema/create-all-tables.sql with CREATE TABLE IF NOT EXISTS
 * for every table. Uses local DB (MYSQL_URL) if available; otherwise extracts from
 * latest backups/YYYY-MM-DD folder. Run: node scripts/generateCreateAllTables.js
 */
import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const SKIP_TABLES = new Set(['SequelizeMeta', 'sequelize_meta']);

/** Extract CREATE TABLE ... ; from a backup file (single table). Returns { tableNameFromFile, ddl }. */
function extractCreateTableFromBackup(content) {
  const match = content.match(/CREATE TABLE `([^`]+)`\s*\([\s\S]*?\)\s*ENGINE=[^;]+;/);
  return match ? { tableNameFromFile: match[1], ddl: match[0] } : null;
}

/** Get table name from backup filename: backup_Products_2026-02-23.sql -> Products (preserves case). */
function tableNameFromBackupFilename(filename) {
  const m = filename.match(/^backup_(.+)_\d{4}-\d{2}-\d{2}\.sql$/);
  return m ? m[1] : null;
}

/** Legacy Products table DDL (app expects `Products` with ProductCode, ProductName, etc.). */
const LEGACY_PRODUCTS_DDL = `CREATE TABLE \`Products\` (
  \`ProductCode\` varchar(50) NOT NULL,
  \`ProductName\` varchar(200) DEFAULT NULL,
  \`ProductFullName\` varchar(255) DEFAULT NULL,
  \`ManufacturerCode\` varchar(50) DEFAULT NULL,
  \`BrandCode\` varchar(50) DEFAULT NULL,
  \`CategoryCode\` int DEFAULT NULL,
  \`SubCategory\` varchar(50) DEFAULT NULL,
  \`UnitOfMeasure\` varchar(50) DEFAULT NULL,
  \`UnitDescription\` varchar(100) DEFAULT NULL,
  \`MRP\` decimal(12,2) DEFAULT 0,
  \`PurchasePrice\` decimal(12,2) DEFAULT 0,
  \`SalePrice\` decimal(12,2) DEFAULT 0,
  \`MinimumStockLevel\` int DEFAULT 0,
  \`ReorderLevel\` int DEFAULT 0,
  \`UniversalProductCode\` varchar(100) DEFAULT NULL,
  \`BarCodeDescription\` varchar(100) DEFAULT NULL,
  \`CommodityCode\` varchar(50) DEFAULT NULL,
  \`HSNId\` varchar(50) DEFAULT NULL,
  \`TaxAmount\` decimal(5,2) DEFAULT 0,
  \`TaxId\` varchar(50) DEFAULT NULL,
  \`Remarks\` text,
  \`CreationDate\` datetime DEFAULT NULL,
  \`ModifiedDate\` datetime DEFAULT NULL,
  \`TotalStock\` int DEFAULT 0,
  \`store_id\` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (\`ProductCode\`),
  KEY \`idx_products_category\` (\`CategoryCode\`),
  KEY \`idx_products_store\` (\`store_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`;

/** Build create-all-tables from backup files in backups/<latestDate>/. Uses filename for table name (correct case). */
function fromBackupFolder() {
  const projectRoot = path.resolve(__dirname, '../..');
  const backupsDir = path.join(projectRoot, 'backups');
  if (!fs.existsSync(backupsDir)) return null;
  const dates = fs.readdirSync(backupsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && /^\d{4}-\d{2}-\d{2}$/.test(d.name))
    .map((d) => d.name)
    .sort()
    .reverse();
  if (dates.length === 0) return null;
  const latestDir = path.join(backupsDir, dates[0]);
  const files = fs.readdirSync(latestDir)
    .filter((f) => f.startsWith('backup_') && f.endsWith('.sql'));
  const tableToDdl = new Map();
  for (const f of files) {
    const nameFromFilename = tableNameFromBackupFilename(f);
    const content = fs.readFileSync(path.join(latestDir, f), 'utf8');
    const extracted = extractCreateTableFromBackup(content);
    if (!extracted) continue;
    const tableName = nameFromFilename || extracted.tableNameFromFile;
    let ddl;
    if (tableName === 'Products' && extracted.ddl.includes('`id` int NOT NULL AUTO_INCREMENT')) {
      ddl = LEGACY_PRODUCTS_DDL;
    } else {
      ddl = extracted.ddl.replace(
        new RegExp(`CREATE TABLE \`${extracted.tableNameFromFile.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``, 'i'),
        `CREATE TABLE \`${tableName}\``
      );
    }
    tableToDdl.set(tableName, ddl);
  }
  return Array.from(tableToDdl.entries()).sort((a, b) => String(a[0]).localeCompare(String(b[0])));
}

async function main() {
  const statements = [
    '-- Generated by backend/scripts/generateCreateAllTables.js',
    '-- Run against local DB to ensure all tables exist (CREATE TABLE IF NOT EXISTS).',
    '',
    'SET FOREIGN_KEY_CHECKS = 0;',
    '',
  ];

  let tablesResolved = false;
  const mysqlUrl = process.env.MYSQL_URL;
  if (mysqlUrl) {
    try {
      const url = new URL(mysqlUrl);
      const config = {
        host: url.hostname,
        port: url.port ? Number(url.port) : 3306,
        user: url.username ? decodeURIComponent(url.username) : undefined,
        password: url.password ? decodeURIComponent(url.password) : undefined,
        database: decodeURIComponent(url.pathname.replace(/^\//, '')) || undefined,
      };
      const conn = await mysql.createConnection(config);
      try {
        const [rows] = await conn.query(
          `SELECT TABLE_NAME AS name FROM information_schema.TABLES
           WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE'
           ORDER BY TABLE_NAME`,
          [config.database]
        );
        const tables = (rows || []).map((r) => r.name).filter((n) => n && !SKIP_TABLES.has(n));
        console.log(`Found ${tables.length} tables from DB.`);
        if (tables.length > 0) {
          for (const tableName of tables) {
            const [showRows] = await conn.query(`SHOW CREATE TABLE \`${tableName}\``);
            const row = Array.isArray(showRows) && showRows[0] ? showRows[0] : null;
            const ddl = row ? (row['Create Table'] || row.CreateTable) : null;
            if (!ddl) {
              console.warn(`No CREATE TABLE for ${tableName}, skipping.`);
              continue;
            }
            const ifNotExists = ddl.replace(/^CREATE TABLE /i, 'CREATE TABLE IF NOT EXISTS ');
            statements.push(`-- ${tableName}`);
            statements.push(ifNotExists + ';');
            statements.push('');
          }
          tablesResolved = true;
        }
      } finally {
        await conn.end();
      }
    } catch (err) {
      console.warn('DB not available, using backup folder:', err.message);
    }
  }

  if (!tablesResolved) {
    const fromBackup = fromBackupFolder();
    if (fromBackup && fromBackup.length > 0) {
      console.log(`Using ${fromBackup.length} tables from latest backup folder.`);
      for (const [tableName, ddl] of fromBackup) {
        const ifNotExists = ddl.replace(/^CREATE TABLE /i, 'CREATE TABLE IF NOT EXISTS ');
        statements.push(`-- ${tableName}`);
        statements.push(ifNotExists);
        statements.push('');
      }
      tablesResolved = true;
    }
  }

  if (!tablesResolved) {
    console.error('No tables from DB and no backup folder found. Create tables manually or run with a populated DB.');
    process.exit(1);
  }

  statements.push('SET FOREIGN_KEY_CHECKS = 1;');
  statements.push('');

  const schemaDir = path.resolve(__dirname, '../schema');
  if (!fs.existsSync(schemaDir)) fs.mkdirSync(schemaDir, { recursive: true });
  const outPath = path.join(schemaDir, 'create-all-tables.sql');
  fs.writeFileSync(outPath, statements.join('\n'), 'utf8');
  console.log(`Wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
