-- Table Backup: Tax
-- Database: Super_Market
-- Date: 2026-02-23
-- Generated: 2026-02-23T14:29:12.827Z

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for table `Tax`
DROP TABLE IF EXISTS `Tax`;
CREATE TABLE `Tax` (
  `Taxcode` int NOT NULL AUTO_INCREMENT,
  `Description` text,
  `Centralsalestax` int DEFAULT NULL,
  `Localsalestax` int DEFAULT NULL,
  `Surcharge` int DEFAULT NULL,
  `Taxonmrp` int DEFAULT NULL,
  `InActive` int DEFAULT NULL,
  `store_id` int DEFAULT NULL,
  `Mrpinclusive` int DEFAULT NULL,
  `CreationDate` text,
  `ModifiedDate` text,
  `CreatedbyUser` text,
  `ModifiedbyUser` text,
  `Taxmode` int DEFAULT NULL,
  `OldCode` text,
  `TaxApplicable` int DEFAULT NULL,
  `CommodityCode` text,
  `CESS` int DEFAULT NULL,
  `FAValueAt` int DEFAULT NULL,
  `SurchargeOnTCS` text,
  `ServiceTax` text,
  `EffectiveTaxPercentage` text,
  `CessBasedOn` text,
  `STAddlTaxBasedOn` text,
  `TaxComputationBasedOn` text,
  `STCess` text,
  `STEducess` text,
  `IsGST` int DEFAULT NULL,
  `GSTCESSBasedOn` text,
  `B2CTaxCode` text,
  PRIMARY KEY (`Taxcode`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table `Tax` (23 rows)
LOCK TABLES `Tax` WRITE;
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (1, 'Excempt', 0, 0, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (2, '28% GST', 14, 14, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (3, '18% GST', 9, 9, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (4, '28%GST + 12% CESS ', 14, 14, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (5, '12% GST', 6, 6, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (6, '5% GST', 3, 3, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (7, '28% GST+12%CESS TAX', 14, 14, 0, 0, 0, 2, 0, '00:00.0', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, '0', 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (8, 'NOTAX', 0, 0, 0, 0, 0, 1, NULL, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (9, '4%', 0, 4, 0, 0, 0, 1, NULL, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (10, '12.50%', 0, 13, 0, 0, 0, 1, NULL, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (11, '14.50%', 0, 15, 0, 0, 0, 1, NULL, '00:00.0', '00:00.0', 'admin1', 'admin1', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (12, '5', 0, 5, 0, 0, 0, 1, NULL, '00:00.0', NULL, 'admin1', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (13, 'IT14.50%', 0, 15, 0, 0, 0, 1, 1, '16:16.2', '00:00.0', 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (14, 'IT5.00%', 0, 5, 0, 0, 0, 1, 1, '16:16.2', '00:00.0', 'Admin', 'Admin', 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (15, 'Exempted', 0, 0, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (16, '5 % GST', 3, 3, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (17, '12 % GST', 6, 6, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (18, '18 % GST', 9, 9, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (19, '28 % GST', 14, 14, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 0, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (20, 'IGST 5 % GST', 5, 0, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 1, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (21, 'IGST 12 % GST', 12, 0, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 1, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (22, 'IGST 18 % GST', 18, 0, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 1, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
INSERT INTO `Tax` (`Taxcode`, `Description`, `Centralsalestax`, `Localsalestax`, `Surcharge`, `Taxonmrp`, `InActive`, `store_id`, `Mrpinclusive`, `CreationDate`, `ModifiedDate`, `CreatedbyUser`, `ModifiedbyUser`, `Taxmode`, `OldCode`, `TaxApplicable`, `CommodityCode`, `CESS`, `FAValueAt`, `SurchargeOnTCS`, `ServiceTax`, `EffectiveTaxPercentage`, `CessBasedOn`, `STAddlTaxBasedOn`, `TaxComputationBasedOn`, `STCess`, `STEducess`, `IsGST`, `GSTCESSBasedOn`, `B2CTaxCode`) VALUES (23, 'IGST 28 % GST', 28, 0, 0, 0, 0, 1, 0, '00:00.0', NULL, 'Admin', NULL, 1, NULL, 0, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'NULL\r');
UNLOCK TABLES;

SET FOREIGN_KEY_CHECKS=1;
